
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComunityBIdSoapPort", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComunityBIdSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.Response
     */
    @WebMethod(operationName = "ComunityBId", action = "ComunityBId")
    @WebResult(name = "Response", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public Response comunityBId(
        @WebParam(name = "Request", targetNamespace = "http://tempuri.org/", partName = "parameters")
        Request parameters);

}
